<?php
$profile = $this->getProfile();
$msQuote = $this->getMsquote();
$shippingAddress = $this->getShippingAddress();
$billingAddress = $this->getBillingAddress();
$paymentMethod = $this->getPaymentMethod();
?>

<div class="page-title title-buttons">
    <h1><?php echo $this->__('Recurring Profile Details')?></h1>
</div>
    <div class="col2-set order-info-box">
        <div class="col-1">
            <table cellspacing="1" class="form-list" width="100%">
                <colgroup>
                    <col width="1">
                    <col width="1">
                </colgroup>
                <tbody>
                <tr>
                    <td class="label"><label><?php echo $this->__('Name')?></label></td>
                    <td class="value"><strong><?php echo $profile->getName()?></strong></td>
                </tr>
                <tr>
                    <td class="label"><label><?php echo $this->__('Frequency')?></label></td>
                    <td class="value"><strong><?php echo $profile->getFrequency()?></strong></td>
                </tr>
                <tr>
                    <td class="label"><label><?php echo $this->__('Start Date')?></label></td>
                    <td class="value"><strong><?php echo $profile->getStartDate()?></strong></td>
                </tr>
                <tr>
                    <td class="label"><label><?php echo $this->__('Status')?></label></td>
                    <td class="value">
                        <strong><?php echo $profile->getStatus($msQuote->getMsorderState())?></strong>
                        <?php
                        if($msQuote->getMsorderState() == Pravams_MySubscription_Model_Msquote::ACTIVE){
                            ?>
                            &nbsp;<a href="<?php echo $this->getUrl('mysubscription/index/changeStatus', array('profile_id' => $profile->getProfileId(), 'status' => Pravams_MySubscription_Model_Msquote::INACTIVE))?>">
                                <?php echo $this->__('Pause Profile');?>
                            </a>
                        <?php
                        }else{
                            ?>
                            &nbsp;<a href="<?php echo $this->getUrl('mysubscription/index/changeStatus', array('profile_id' => $profile->getProfileId(), 'status' => Pravams_MySubscription_Model_Msquote::ACTIVE))?>">
                                <?php echo $this->__('Start Profile');?>
                            </a>
                        <?php
                        }
                        ?>
                    </td>
                </tr>
                </tbody>
            </table>
        </div>
    </div>
    <div class="col2-set order-info-box">
        <div class="col-1">
            <h4><?php echo $this->__('Billing Address')?></h4>
            <address>
                <?php echo $billingAddress->getFirstname()?> <?php echo $billingAddress->getLastname()?><br />
                <?php echo $billingAddress->getCompany()?><br />
                <?php echo $billingAddress->getStreet()?><br />
                <?php echo $billingAddress->getCity()?>, <?php echo $billingAddress->getRegion()?> <?php echo $billingAddress->getPostcode() ?><br />
                <strong>T</strong> | <?php echo $billingAddress->getTelephone();
                if($billingAddress->getFax()):?>
                    <br /><strong>F</strong> | <?php echo $billingAddress->getFax() ?>
                <?php endif;?>
            </address>
        </div>
        <?php if(!$msQuote->getIsVirtual()) { ?>
        <div class="col-2">
            <h4><?php echo $this->__('Shipping Address')?></h4>
            <address>
                <?php echo $shippingAddress->getFirstname()?> <?php echo $shippingAddress->getLastname()?><br />
                <?php echo $shippingAddress->getCompany() ?><br />
                <?php echo $shippingAddress->getStreet() ?><br />
                <?php echo $shippingAddress->getCity()?>, <?php echo $shippingAddress->getRegion()?> <?php echo $shippingAddress->getPostcode()?><br />
                <strong>T</strong> | <?php echo $shippingAddress->getTelephone();
                if($shippingAddress->getFax()):?>
                    <br /><strong>F</strong> | <?php echo $shippingAddress->getFax() ?>
                <?php endif;?>

            </address>
        </div>
        <?php }?>
    </div>
    <br />
    <div class="col2-set order-info-box">
        <div class="col-1">
            <h4><?php echo $this->__('Payment Method')?></h4>
            <?php echo $paymentMethod->getMethod()?>
        </div>
        <?php if(!$msQuote->getIsVirtual()) { ?>
        <div class="col-2">
            <h4><?php echo $this->__('Shipping Method')?></h4>
            <?php echo $this->escapeHtml($shippingAddress->getShippingMethod())?> <?php echo $this->escapeHtml($shippingAddress->getShippingDescription())?>
        </div>
        <?php }?>
    </div>
    <br />
    <h4><?php echo $this->__('Items Ordered')?></h4>
    <table class="data-table">
        <thead>
        <tr>
            <th><?php echo $this->__('Product Name')?></th>
            <th class="a-right" width="15%"><?php echo $this->__('Price')?></th>
            <th class="a-center" width="10%"><?php echo $this->__('Sku')?></th>
            <th class="a-center" width="10%"><?php echo $this->__('Qty')?></th>
            <th class="a-right" width="20%"><?php echo $this->__('Subtotal')?></th>
        </tr>
        </thead>
        <tbody>
            <?php echo $this->getChildHtml('mysubscription.profile.view.items');?>
        </tbody>
        <tfoot>
            <?php echo $this->getChildHtml('mysubscription.profile.view.totals');?>
        </tfoot>
    </table>
    <br />
    <div>
        <a href="<?php echo $this->getUrl('mysubscription/index/list')?>"><small>&laquo;</small> <?php echo $this->__('Back')?></a>
    </div>