<?php
$msQuote = $this->getMsquote();
$shippingAddress = $this->getShippingAddress();
?>
<tr>
    <td colspan="4" class="a-right"><?php echo $this->__('Subtotal')?></td>
    <td class="a-right"><?php echo Mage::helper('mysubscription')->formatPrice($shippingAddress->getSubtotal())?></td>
</tr>
<tr>
    <td colspan="4" class="a-right"><?php echo $this->__('Shipping & Handling')?></td>
    <td class="a-right"><?php echo Mage::helper('mysubscription')->formatPrice($shippingAddress->getShippingAmount())?></td>
</tr>
<tr>
    <td colspan="4" class="a-right"><?php echo $this->__('Tax')?></td>
    <td class="a-right"><?php echo Mage::helper('mysubscription')->formatPrice($shippingAddress->getTaxAmount())?></td>
</tr>
<tr class="grand-total last">
    <td colspan="4" class="a-right"><strong><?php echo $this->__('Grand Total')?></strong></td>
    <td class="a-right"><strong><?php echo Mage::helper('mysubscription')->formatPrice($shippingAddress->getGrandTotal())?></strong></td>
</tr>