<?php
/**
 * Pravams MySubscription Module
 *
 * @category    Pravams
 * @package     Pravams_MySubscription
 * @copyright   Copyright (c) 2014 Pravams LLC. (http://www.pravams.com)
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<div class="block block-progress opc-block-progress">
    <div class="block-title">
        <strong><span><?php echo $this->__('Your Checkout Progress') ?></span></strong>
    </div>
    <div class="block-content">
        <dl>
            <?php if(Mage::getSingleton('mysubscription/cart')->getMsquote()->hasItems()){?>
                <?php if ($this->getCheckout()->getStepData('mysubscription', 'is_show')):?>
                    <div id="mysubscription-progress-checkout">
                        <?php echo $this->getChildHtml('mysubscription.progress');?>
                    </div>
                <?php endif;?>
            <?php }?>
            <?php if ($this->getCheckout()->getStepData('billing', 'is_show')): ?>
                <div id="billing-progress-opcheckout">
                    <?php echo $this->getChildHtml('billing.progress') ?>
                </div>
            <?php endif; ?>

            <?php if ($this->getCheckout()->getStepData('shipping', 'is_show')): ?>
                <div id="shipping-progress-opcheckout">
                    <?php echo $this->getChildHtml('shipping.progress') ?>
                </div>
            <?php endif; ?>

            <?php if ($this->getCheckout()->getStepData('shipping_method', 'is_show')): ?>
                <div id="shipping_method-progress-opcheckout">
                    <?php echo $this->getChildHtml('shippingmethod.progress') ?>
                </div>
            <?php endif; ?>

            <?php if ($this->getCheckout()->getStepData('payment', 'is_show')): ?>
                <div id="payment-progress-opcheckout">
                    <?php echo $this->getChildHtml('payment.progress') ?>
                </div>
            <?php endif; ?>
        </dl>
    </div>
</div>

