<?php
/**
 * Pravams MySubscription Module
 *
 * @category    Pravams
 * @package     Pravams_MySubscription
 * @copyright   Copyright (c) 2014 Pravams LLC. (http://www.pravams.com)
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<div class="page-title">
    <h1><?php echo $this->__('Your Subscription Request has been saved to your profile')?></h1>
</div>
<h2 class="sub-title"><?php echo $this->__('Thank you for your purchase!');?></h2>

<div class="buttons-set">
    <button type="button" class="button" title="<?php echo $this->__('Continue Shopping')?>" onclick="window.location='<?php echo $this->getUrl()?>'"><span><span><?php echo $this->__('Continue Shopping')?></span></span></button>
</div>