<?php
/**
 * Pravams MySubscription Module
 *
 * @category    Pravams
 * @package     Pravams_MySubscription
 * @copyright   Copyright (c) 2014 Pravams LLC. (http://www.pravams.com)
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<?php
$msQuote = $this->getMsquote();
//$msItemsCollection =  $msQuote->getItemsCollection();
$msItemsCollection =  Mage::helper('mysubscription')->getMscartItems();
?>
<?php
foreach($msItemsCollection as $_msItem){?>
    <tr>
        <td><h3 class="product-name"><?php echo $_msItem->getName();?></h3></td>
        <td class="a-right"><?php echo Mage::helper('mysubscription')->formatPrice($_msItem->getPrice())?></td>
        <td class="a-center"><?php echo Mage::helper('mysubscription')->formatQty($_msItem->getQty())?></td>
        <td class="a-right"><?php echo Mage::helper('mysubscription')->formatPrice($_msItem->getRowTotal())?></td>
    </tr>
<?php }
?>