<?php
$msQuote = $this->getMsquote();
if(!$msQuote->getIsVirtual()){
    $msAddress = $this->getShippingAddress();
}else{
    $msAddress = $this->getBillingAddress();
}

?>
<tr>
    <td colspan="4" class="a-right"><?php echo $this->__('Subtotal')?></td>
    <td class="a-right"><?php echo Mage::helper('mysubscription')->formatPrice($msAddress->getSubtotal())?></td>
</tr>
<?php if(!$msQuote->getIsVirtual()){ ?>
<tr>
    <td colspan="4" class="a-right"><?php echo $this->__('Shipping & Handling')?></td>
    <td class="a-right"><?php echo Mage::helper('mysubscription')->formatPrice($msAddress->getShippingAmount())?></td>
</tr>
<?php }?>
<tr>
    <td colspan="4" class="a-right"><?php echo $this->__('Tax')?></td>
    <td class="a-right"><?php echo Mage::helper('mysubscription')->formatPrice($msAddress->getTaxAmount())?></td>
</tr>
<tr class="grand-total last">
    <td colspan="4" class="a-right"><strong><?php echo $this->__('Grand Total')?></strong></td>
    <td class="a-right"><strong><?php echo Mage::helper('mysubscription')->formatPrice($msAddress->getGrandTotal())?></strong></td>
</tr>